apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    app: tool
    service: notifier
spec:
  selector:
    matchLabels:
      app: tool
      service: notifier
  template:
    metadata:
      labels:
        app: tool
        service: notifier
    spec:
      restartPolicy: Always
      containers:
      - name: notifier-container
        image: "cvando/notifier_rancher_victorops-citadel:latest"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8090
        resources: 
          requests:
            cpu: 0.1
            memory: 100Mi
          limits:
            cpu: 0.1
            memory: 100Mi
        volumeMounts:
        - mountPath: /env
          name: env-volume
      initContainers:
      - name: vault-retrieve
        image: cvando/vault-init
        imagePullPolicy: Always
        env:
          - name: VAULT_PATH
            valueFrom:
              secretKeyRef:
                name: vault-sercret
                key: vault_path
          - name: VAULT_URL
            valueFrom:
              secretKeyRef:
                name: vault-sercret
                key: vault_url
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault-sercret
                key: vault_token
        volumeMounts:
        - mountPath: /env
          name: env-volume
      volumes:
      - name: env-volume
        emptyDir:
          medium: Memory
