apiVersion: v1
kind: Service
metadata:
  name: notifier
  labels:
    app: tool
    service: notifier
spec:
  selector:
    app: tool
    service: notifier
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
    name: http